[[character]]
  name = "reimu"
  display_name = "博丽灵梦"
  hp = 20
  atk = 256

  [[spellcard]]
    name = "[灵符] 梦想封印"
    harm = [0, 4]
    atk = [0, 0]
    shield = 0
    hp = 0

  [[spellcard]]
    name = "梦想天生"
    harm = [3, 4]
    atk = [50, 2]
    shield = 1
    hp = 0

  [[spellcard]]
    name = "[梦符] 封魔阵"
    harm = [0, 4]
    atk = [0, 0]
    shield = 1
    hp = 0
  
[[character]]
  name = "marisa"
  display_name = "雾雨魔理沙"
  atk = 300
  hp = 18

  [[spellcard]]
    name = "[恋符] Master Spark"
    harm = [1, 4]
    atk = []



    